# Generated by Django 2.2.3 on 2019-07-11 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlfiles', '0002_dlfile_posted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlfile',
            name='file_token',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
