# Generated by Django 2.2.3 on 2019-07-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlfiles', '0003_dlfile_file_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='dlfile',
            name='token_sent',
            field=models.BooleanField(default=False),
        ),
    ]
