# Generated by Django 2.2.2 on 2019-06-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_file_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='downloadable_during',
            field=models.CharField(max_length=100),
        ),
    ]
